name: Cleanup Workflow Runs

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all workflow runs
        env:
          BOT_TOKEN: ${{ secrets.BOT }}
          REPOSITORY: ${{ github.repository }}
        run: |
          page=1
          while true; do
            response=$(curl -sS -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $BOT_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$REPOSITORY/actions/runs?per_page=100&page=$page")
            run_ids=$(echo "$response" | jq -r '.workflow_runs[].id')
            if [ -z "$run_ids" ]; then
              break
            fi
            for run_id in $run_ids; do
              curl -sS -L -X DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $BOT_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/$REPOSITORY/actions/runs/$run_id"
            done
            page=$((page + 1))
          done
