name: Fetch PRs Counts

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
  
        - name: Install Axios
          run: npm install axios

        - name: Run Fetch closed PRs Script 
          env:
            PAT: ${{ secrets.PAT }}
          run: node ./scripts/fetch_closed_prs.js

        - name: Run Fetch closed PRs labels Script 
          env:
            PAT: ${{ secrets.PAT1 }}
          run: node ./scripts/fetch_closed_PRs_labels.js
        
        - name: Run Fetch open PRs Script 
          env:
            PAT: ${{ secrets.PAT2 }}
          run: node ./scripts/fetch_open_PRs_labels.js

        - name: Run Fetch all states PRs Script 
          env:
            PAT: ${{ secrets.PAT }}
          run: node ./scripts/fetch_all_states_PRs_labels.js 
        

        - name: Commit and Push Changes
          env:
            PAT: ${{ secrets.PAT }}
          run: |
            git config --local user.name "PCL-Community-Bot"
            git config --local user.email "167983016+PCL-Community-Bot@users.noreply.github.com"
            git add .
            git commit -m "Update PRs counts" || echo "No changes to commit"
            git push "https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git" HEAD:main
            
        - name: Trigger auto-update.yml
          if: success()
          env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
          run: |
           curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Deep-Dark-Forest/PCL2-GitHub-Dashboard-Homepage/actions/workflows/auto-update.yml/dispatches \
            -d '{"ref": "main"}'   
