name: Get Issue Labels Count

on:
  schedule:
    - cron: '*/15 * * * *'  # 每 15 分钟执行一次

jobs:
  get-labels-count:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Labels and Issues Count
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 获取所有标签
        labels=$(curl -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/Hex-Dragon/PCL2/labels \
          | jq -r '.[].name')

        # 清空或创建 data.md 文件
        echo "" > data.md

        # 对每个标签获取其 open issue 数量并追加到 data.md 文件中
        for label in $labels; do
          # URL encode the label to handle special characters
          encoded_label=$(echo "$label" | jq -sRr @uri)

          # 使用编码后的标签进行查询
          issue_count=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=repo:Hex-Dragon/PCL2+label:$encoded_label+state:open" \
            | jq '.total_count')

          # 将结果写入 data.md
          echo "$label $issue_count" >> data.md
        done

    - name: Commit and Push Changes if data.md is modified
      run: |
        # 检查 data.md 文件是否有变化
        if [ -n "$(git status --porcelain data.md)" ]; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.md
          git commit -m "Update issue counts for labels"
          git push
        else
          echo "No changes in data.md, skipping commit and push."