name: Update Issue Count

on:
  schedule:
    - cron: "*/15 * * * *"  # 每 15 分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-issue-count:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests library
      run: pip install requests

    - name: Fetch labels and issues count
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Actions 自动生成的令牌
      run: |
        import os
        import re
        import requests

        # GitHub API 访问目标仓库
        REPO_OWNER = "Hex-Dragon"
        REPO_NAME = "PCL2"
        API_URL = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/labels"

        headers = {
            "Authorization": f"Bearer {os.getenv('GITHUB_TOKEN')}",
            "Accept": "application/vnd.github.v3+json"
        }

        # 获取所有标签
        response = requests.get(API_URL, headers=headers)
        if response.status_code != 200:
            raise Exception(f"Failed to fetch labels: {response.status_code} {response.text}")

        labels = response.json()

        for label in labels:
            label_name = label['name']
            # 获取该标签下的issue数量
            issues_url = f"https://api.github.com/search/issues?q=label:{label_name}+repo:{REPO_OWNER}/{REPO_NAME}+type:issue"
            issues_response = requests.get(issues_url, headers=headers)
            if issues_response.status_code != 200:
                raise Exception(f"Failed to fetch issues for label {label_name}: {issues_response.status_code} {issues_response.text}")

            issues_data = issues_response.json()
            issue_count = issues_data['total_count']

            # 处理标签名中的特殊字符
            safe_label_name = re.sub(r'[\/:*?"<>| ]', '_', label_name)

            # 保存到文件 [标签名].md
            with open(f"{safe_label_name}.md", "w") as file:
                file.write(str(issue_count) + '\n')

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update issue count for labels"
        git push
      continue-on-error: true  # 如果没有文件更新，不要让工作流失败